config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'
Rails.application.routes.draw do
 resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end
  resources :feeds
  resources :planet, only: [:index,:show]
  resources :preferences, only: [:index,:update]
  resources :oportunities
  resources :profile_views
  resources :conversations, only: [:index,:create,:new] do
    resources :messages, only: [:index,:create]
  end

  get 'communities/:community/events' => 'events#index', as: 'community_events'
  get 'communities/:community_id/contacts/preview' => "contacts#preview", as: 'community_contact_preview'
  resources :badge_rules
  get 'badges/:uuid/claim' => "badges#claim", as: 'badge_claim'
  get 'badges/:uuid/qrcode' => "badges#qrcode", as: 'qrcode_badge'
  get 'badges/:id/assertion' => "badges#assertion", as: 'badge_assertion'
  resources :badges
  resources :attendees
  resources :tickets
  resources :ticket_types

  resources :notifications, only: [:index,:update]
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/badges/:event_id" => "badges#index", as: "event_badges"
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  #get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  #get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  get 'users/:id/badges' => 'user#assertions', as: 'user_badges'
  get 'users/events' => 'user#events', as: 'my_events'
  get 'users/news' => 'user#news', as: 'my_news'
  get 'events/:id/invitations' => 'events#invites', as: 'event_invites'
  post 'events/:id/unique' => 'events#unique', as: 'unique_event'
  post 'events/unique' => 'events#unique', as: 'new_unique_event'
  post 'events/:event_id/attendees/draw' => 'attendees#draw', as: 'draw_attendees'

  resources :events do
    resources :attendees, only: [:index]
    resources :schedule, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities do
    resources :members
    resources :invites
    resources :boards do
      resources :board_messages, only: [:new,:edit,:show,:update,:create,:destroy]
    end
    resources :contacts
  end
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/controllers/profile_views_controller.rb
class ProfileViewsController < ApplicationController
  before_action :set_profile_view, only: [:show, :edit, :update, :destroy]

  # GET /profile_views
  # GET /profile_views.json
  def index
    @profile_views = ProfileView.all
  end

  # GET /profile_views/1
  # GET /profile_views/1.json
  def show
  end

  # GET /profile_views/new
  def new
    @profile_view = ProfileView.new
  end

  # GET /profile_views/1/edit
  def edit
  end

  # POST /profile_views
  # POST /profile_views.json
  def create
    @profile_view = ProfileView.new(profile_view_params)

    respond_to do |format|
      if @profile_view.save
        format.html { redirect_to @profile_view, notice: t(:was_successfully_created) }
        format.json { render :show, status: :created, location: @profile_view }
      else
        format.html { render :new }
        format.json { render json: @profile_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_views/1
  # PATCH/PUT /profile_views/1.json
  def update
    respond_to do |format|
      if @profile_view.update(profile_view_params)
        format.html { redirect_to @profile_view, notice: t(:was_successfully_updated) }
        format.json { render :show, status: :ok, location: @profile_view }
      else
        format.html { render :edit }
        format.json { render json: @profile_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_views/1
  # DELETE /profile_views/1.json
  def destroy
    @profile_view.destroy
    respond_to do |format|
      format.html { redirect_to profile_views_url, notice: t(:was_successfully_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_view
      @profile_view = ProfileView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_view_params
      params.require(:profile_view).permit(:name)
    end
end

app/helpers/profile_views_helper.rb
module ProfileViewsHelper
end

app/views/profile_views/_form.html.slim
= form_for @profile_view do |f|
  - if @profile_view.errors.any?
    #error_explanation
      h2 = "#{pluralize(@profile_view.errors.count, "error")} prohibited this profile_view from being saved:"
      ul
        - @profile_view.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/profile_views/edit.html.slim
h1 Editing profile_view

== render 'form'

=> link_to 'Show', @profile_view
'|
=< link_to 'Back', profile_views_path

app/views/profile_views/index.html.slim
h1 Listing profile_views

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @profile_views.each do |profile_view|
      tr
        td = profile_view.name
        td = link_to 'Show', profile_view
        td = link_to 'Edit', edit_profile_view_path(profile_view)
        td = link_to 'Destroy', profile_view, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Profile view', new_profile_view_path

app/views/profile_views/new.html.slim
h1 New profile_view

== render 'form'

= link_to 'Back', profile_views_path

app/views/profile_views/show.html.slim
p#notice = notice

p
  strong Name:
  = @profile_view.name

=> link_to 'Edit', edit_profile_view_path(@profile_view)
'|
=< link_to 'Back', profile_views_path