config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'
Rails.application.routes.draw do
 resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end
  resources :feeds
  resources :planet, only: [:index,:show]
  resources :preferences, only: [:index,:update]
  resources :oportunities
  resources :profile_views
  resources :conversations, only: [:index,:create,:new] do
    resources :messages, only: [:index,:create]
  end

  get 'communities/:community/events' => 'events#index', as: 'community_events'
  get 'communities/:community_id/contacts/preview' => "contacts#preview", as: 'community_contact_preview'
  resources :badge_rules
  get 'badges/:uuid/claim' => "badges#claim", as: 'badge_claim'
  get 'badges/:uuid/qrcode' => "badges#qrcode", as: 'qrcode_badge'
  get 'badges/:id/assertion' => "badges#assertion", as: 'badge_assertion'
  resources :badges
  resources :attendees
  resources :tickets
  resources :ticket_types

  resources :notifications, only: [:index,:update]
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/badges/:event_id" => "badges#index", as: "event_badges"
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  #get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  #get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  get 'users/:id/badges' => 'user#assertions', as: 'user_badges'
  get 'users/events' => 'user#events', as: 'my_events'
  get 'users/news' => 'user#news', as: 'my_news'
  get 'events/:id/invitations' => 'events#invites', as: 'event_invites'
  post 'events/:id/unique' => 'events#unique', as: 'unique_event'
  post 'events/unique' => 'events#unique', as: 'new_unique_event'
  post 'events/:event_id/attendees/draw' => 'attendees#draw', as: 'draw_attendees'

  resources :events do
    resources :attendees, only: [:index]
    resources :schedule, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities do
    resources :members
    resources :invites
    resources :boards do
      resources :board_messages, only: [:new,:edit,:show,:update,:create,:destroy]
    end
    resources :contacts
  end
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :user, foreign_key: :owner_id
  has_many :user_badges
  has_many :users, through: :user_badges
  belongs_to :badgeble, polymorphic: true
  belongs_to :badge_rule
  has_attached_file :image,
              style: {openbadges: ["90x90", :png],
                      original: [:png]}
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/png","image/svg"] }, size: { in: 0..256.kilobytes }
  validate :image_dimensions, :on => :create

  def apply_rule(user_id)
    claim = false
    rule = self.badge_rule
    if rule.inmediatly
      claim = true if rule.times == rule.badgeble_type.constantize.find(rule.relation_class.to_sym => user_id).count
    else
      claim =  true unless self.badgeble.send(rule.relation_class).where(:user_id => user_id).first.nil?
    end
    return claim
  rescue
    logger.debug rule.inspect
    return false
  end


  private

    def image_dimensions
        required_width  = 90
        required_height = 90
        dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)

        errors.add(:image, "El ancho de la imagen tiene que ser de #{required_width}px") unless dimensions.width.to_i == required_width.to_i
        errors.add(:image, "El alto de la image tiene que ser de #{required_height}px") unless dimensions.height.to_i == required_height.to_i
      end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:show]
  before_action :set_badge, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # Claim badges will get the user a badges
  # GET /badges/claim/id
  def qrcode
    @badge= Badge.find_by_uuid(params[:uuid])
    unless @badge.nil?
      @qr = RQRCode::QRCode.new( badge_claim_url(@badge.uuid), :size => 8, :level => :h )
    else
      redirect_to badges_url, notice: t(:badge_not_found)
    end
  rescue RQRCode::QRCodeRunTimeError => e
    logger.info "Manage qr error show #{e.inspect}"
  end

  def claim
    unless params[:uuid].nil?
      @badge = Badge.find_by_uuid(params[:uuid])
      unless @badge.nil?
        unless current_user.user_badges.where(badge_id: @badge.id).first.nil?
          redirect_to user_custom_url(current_user.id,current_user.name),
                notice: t(:you_have_already_clame_this_badge,
                badge_name: @badge.name)
        else
          if @badge.claim_until >= Date.today && @badge.expire > Date.today
            if  @badge.apply_rule(current_user.id)
              @user_badge = current_user.user_badges.new(badge_id: @badge.id)
              if @user_badge.save
                redirect_to user_custom_url(current_user.id,current_user.name),
                    notice: t(:congratulations_you_have_earn_a_new_badge,user_name: current_user.name,badge_name: @badge.name)
              end
            else
              redirect_to badges_url,notice: t(:badge_claim_rule_fail,name: @badge.badgeble.name)
            end
          else
            redirect_to badges_url,notice: t(:badge_claim_expiration_has_been_reach)
          end
        end
      else
        redirect_to badges_url, notice: t(:badge_not_found)
      end
    end
  rescue Exception => e
    logger.debug e.message
    redirect_to badges_url, notice: t(:something_when_wrong)
  end

  def assertion
    user_badge = UserBadge.find(params[:id])
    assertion = OpenBadges::Assertion.new
    # You'd probably fill in these values from some `badges` table and
    # user information
    assertion.email = user_badge.user.email
    assertion.issued_on = Time.now
    assertion.name = user_badge.badge.name
    assertion.description = user_badge.badge.description
    assertion.badge_url = "https://floss-pa.net/badges/1"
    assertion.criteria_url = "https://floss-pa.net/badges/1"

    render json: assertion
  end
  # GET /badges
  # GET /badges.json
  def index
    if params[:event_id].nil?
      @badges = Badge.paginate(:page => params[:page],:per_page => 15).order("id desc")
      @user = UserBadge.last.nil? ? nil : UserBadge.last.user
      @badge = UserBadge.last.badge
    else
      @event = Event.find(params[:event_id])
      @badges = @event.badges.paginate(:page => params[:page],:per_page => 15).order("id desc")
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @users = @badge.users.paginate(:page => params[:page],:per_page => 24).order("id desc")
  end

  # GET /badges/new
  def new
    @badge = Badge.new
    @badgeble = nil
    unless params[:event_id].nil?
      @badgeble = Event.find(params[:event_id])
      @badge.claim_until = @badgeble.start_at.next_day
      @badge.expire = @badgeble.end_at.next_day
    end
  end

  # GET /badges/1/edit
  def edit
    @badgeble = @badge.badgeble
    unless @badgeble.nil?
      @badge.claim_until = @badgeble.start_at.next_day
      @badge.expire = @badgeble.end_at.next_day
    end
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)
    @badge.owner_id = current_user.id
    @badge.uuid = SecureRandom.uuid
    unless params[:badgeble_id].nil?
      @badge.badgeble_id = params[:badgeble_id]
      @badge.badgeble_type = params[:badgeble_type]
      @badgeble = params[:badgeble_type].constantize.find(params[:badgeble_id])
    end
    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: t(:was_successfully_created) }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: t(:was_successfully_updated) }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: t(:was_successfully_destroyed) }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:owner_id, :name, :description, :criteria, :expire, :tags, :claim_until,:image,:badge_rule_id)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_badge.html.slim
div class="list-group-item col-lg-2 text-center" style="border: 0;"
    = link_to(badge_path(badge.id), title: "#{badge.name} - #{t(:awarded,times: badge.user_badges.count)}" , data: {toggle: "tooltip", container: "body", placement: "bottom"})  do
      = image_tag badge.image.url, size: "90x90"
    - if user_signed_in?
      br
      - if badge.owner_id==current_user.id
        = link_to t(:edit), edit_badge_path(badge.id)
      - if badge.claim_until>=Date.today && badge.expire>Date.today
        '|
        = link_to t(:claim), badge_claim_path(badge.uuid)
        '|
        = link_to t(:qrcode), qrcode_badge_path(badge.uuid)

app/views/badges/_form.html.slim
= form_for @badge, html: { multipart: true } do |f|
  - if @badge.errors.any?
    #error_explanation
      h2 = "#{pluralize(@badge.errors.count, "error")} prohibited this badge from being saved:"
      ul
        - @badge.errors.full_messages.each do |message|
          li = message

  div class="col-lg-6"
    div class="form-group row"
      = f.label t(:name) + ":", class: "form-input-label"
      = f.text_field :name, required: true, pattern: "[-0-9A-Za-zÀ-ÿ\s]{1,50}", minlength: "6", maxlenght: "100", class: "form-control"
      = hidden_field_tag 'badgeble_id', @badgeble.id, class: "form-control" unless @badgeble.nil?
      = hidden_field_tag 'badgeble_type', @badgeble.class.name unless @badgeble.nil?
      div class="text-warning"
        | * &nbsp;
        = t(:required) + ", " + t(:max_length, num_chars: 50)
    div class="form-group row"
      = f.label t(:description) + ":", class: "form-input-label"
      = f.text_field :description, required: true, minlength: "6", maxlenght: "250", class: "form-control"
      div class="text-warning"
        | * &nbsp;
        = t(:required)
  div class="col-lg-6 text-center"
    = image_tag @badge.image.url unless @badge.nil?
  div class="col-lg-12"
  div class="col-lg-6"
    div class="text-warning"
      - if @badgeble.class.name == "Event"
        = t(:badge_criterial_information)
        br
        = t(:event_badges)
  div class="col-lg-6"
    div class="form-group"
      = f.label t(:image) + ":", class: "form-input-label"
      = f.file_field :image, required: true, class: 'form-control'
      div class="text-warning"
        = t(:badge_image_instructions)
  div class="col-lg-12"
    div class="form-group row"
      = f.label t(:rule) + ":", class: "form-input-label"
      = f.select :badge_rule_id, BadgeRule.where("inmediatly=false and badgeble_type=?",@badgeble.class.name).collect {|p| [p.name, p.id]}, required: true
  div class="col-lg-12"
    div class="form-group row"
      = f.label t(:criteria) + ":", class: "form-input-label"
      = f.text_field :criteria, required: true, minlength: "6", maxlenght: "50", class: "form-control"
      div class="text-warning"
        | * &nbsp;
        = t(:required) + ", " + t(:criteria_info)
  div class="col-lg-12"
    div class="form-group row"
      = f.label t(:expire) + ": ", class: "form-input-label col-lg-2 row"
      = f.text_field :expire, value: (f.object.expire.strftime("%Y-%m-%d") unless f.object.expire.nil? ),required: true, "data-provide": "datepicker", "data-date-format": "yyyy-mm-dd", placeholder: DateTime.now.strftime("%Y-%m-%d"), class: "col-lg-2"
      div class="text-info col-lg-6 row"
        | &nbsp; * &nbsp;
        = t(:expire_info)
  div class="col-lg-10"
  div class="col-lg-12"
    div class="form-group row"
      = f.label t(:tags), class: "form-input-label"
      = f.text_field :tags, class: "form-control"
      div class="text-info"
        = t(:tags_info)
  div class="col-lg-12"
    div class="form-group row"
      = f.label t(:claim_until) + ": ", class: "form-input-label col-lg-2 row"
      = f.text_field :claim_until, value: (f.object.claim_until.strftime("%Y-%m-%d") unless f.object.claim_until.nil? ),required: true, "data-provide": "datepicker", "data-date-format": "yyyy-mm-dd", placeholder: DateTime.now.strftime("%Y-%m-%d"), class: "col-lg-2"
      div class="text-warning col-lg-6 row"
        | &nbsp; * &nbsp;
        = t(:required) + ", " + t(:claim_info)
  div class="col-lg-12"
    div class="form-group row"
      .actions = f.submit

app/views/badges/claim.html.slim
div class="container"
 div class="bs-docs-section clearfix"
  div class="row"
    div class="page-header"
    div class="col-lg-12 text-center"
      = t(:congratulations)
      | &nbsp;
      = link_to current_user.name,user_custom_url(current_user.id,current_user.name)
      | &nbsp;
      = t(:you_have_earn_a_new_badge)
      br
      = image_tag @user_badge.badge.image.url, size: "90x90" unless @user_badge.nil?
      br
      = @user_badge.badge.name unless @user_badge.nil?
      br
      = @user_badge.badge.description unless @user_badge.nil?

app/views/badges/edit.html.slim
div class="container"
 div class="col-lg-12"
    div class="page-header"
      h3 = t(:editing_badge)
    div class="col-lg-12"
      == render 'form'
    => link_to t(:show), @badge
    '|
    =< link_to t(:back), badges_path

app/views/badges/index.html.slim
div class="container"
    div class="page-header"
     - unless @event.nil?
        = render @event
        div class="col-lg-12 text-center"
          = t(:event_badges_title)
     - else
       = t(:site_badges)
    div class="col-lg-12 text-center"
       - if @badges.count.to_i<3.to_i
         div class="col-lg-10 text-center"
           = link_to t(:add_badge_to_event), new_badge_path(:event_id=> @event.id) unless @event.nil?
    dic class="col-lg-2"
      - if @event.nil?
       - unless @badge.nil?
         div class="text-center"
           = t(:last_awarded)
           br
           br
           = image_tag @badge.image.url, size: "90x90"
           br
           = @badge.name
           br
           = t(:awarded,times: @badge.user_badges.count)
           br
           br
           = t(:last_awarded_to)
           br
           = link_to(user_custom_path(@user.id,@user.name.gsub(/\s/,'-')), title: "#{@user.name}" , data: {toggle: "tooltip", container: "body", placement: "bottom"})  do
             = image_tag @user.avatar.url(:med_thumb),size: "90x90", alt: @user.name, class: "img-circle img-fluid"
    div class="col-lg-10"
       = will_paginate @badges, renderer: BootstrapPagination::Rails
       div class="panel panel-default"
         div class="panel-heading"
           = t(:all_badges)
         div class="panel-body"

           div class="list-group"
             - @badges.each do |badge|
               = render badge
       = will_paginate @badges, renderer: BootstrapPagination::Rails

app/views/badges/new.html.slim
div class="container"
 div class="col-lg-12"
    div class="page-header"
      h3 = t(:new_bage)
    div class="col-lg-12"
      == render 'form'
    = link_to t(:back), badges_path

app/views/badges/qrcode.html.slim
div class="container"
 div class="col-lg-12"
    div class="page-header"
      - if notice
        div class="col-lg-12"
          div class="alert alert-dismissible alert-success"
            button type="button" class="close" data-dismiss="alert"
              | &times;
            = notice
    div class="col-lg-4"
    div class="col-lg-3"
      css:
          #qr table {
            border-width: 0;
            border-style: none;
            border-color: #0000ff;
            border-collapse: collapse;
            text-align: center;
            }
          #qr td {
            border-left: solid 5px #000;
            padding: 0;
            margin: 0;
            width: 0px;
            height: 5px;
            }
          #qr td.black { border-color: #000; }
          #qr td.white { border-color: #fff; }
      div id="qr"
        = raw @qr.as_html
      p class="text-center"
        = @badge.name

app/views/badges/show.html.slim
div class="container"
 div class="col-lg-12"
    div class="page-header"
      = @badge.name
    div class="col-lg-2 text-center"
      = image_tag @badge.image.url, size: "90x90"
    div class="col-lg-10"
      div class="panel panel-default"
        div class="panel-heading"
          = t(:badge_info)
        div class="panel-body"
          p
            strong
              = t(:tags) + ": "
            = @badge.tags
          p
            strong
              = t(:description) + ": "
            = @badge.description
          p
            strong
              = t(:criteria) +": "
            = @badge.criteria
          p
            strong
              = t(:expire) + ": "
            = @badge.expire
          p
            strong
              = t(:claim_until) +": "
            = @badge.claim_until
      - unless @users.empty?
        div class="panel panel-default"
          div class="panel-heading"
            = t(:badge_awarded)
          div class="panel-body"
            div class="list-group"
              - @users.each do |user|
                div class="list-group-item col-lg-2 text-center" style="border: 0;"
                   = link_to(user_custom_path(user.id,user.name.gsub(/\s/,'-')), title: "#{user.name}" , data: {toggle: "tooltip", container: "body", placement: "bottom"})  do
                     = image_tag user.avatar.url(:med_thumb),size: "90x90", alt: user.name, class: "img-circle img-fluid"
      div class="col-lg-10 text-center"
        = will_paginate @users, renderer: BootstrapPagination::Rails
      => link_to 'Edit', edit_badge_path(@badge)
      '|
      =< link_to 'Back', badges_path