config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'
Rails.application.routes.draw do
 resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end
  resources :feeds
  resources :planet, only: [:index,:show]
  resources :preferences, only: [:index,:update]
  resources :oportunities
  resources :profile_views
  resources :conversations, only: [:index,:create,:new] do
    resources :messages, only: [:index,:create]
  end

  get 'communities/:community/events' => 'events#index', as: 'community_events'
  get 'communities/:community_id/contacts/preview' => "contacts#preview", as: 'community_contact_preview'
  resources :badge_rules
  get 'badges/:uuid/claim' => "badges#claim", as: 'badge_claim'
  get 'badges/:uuid/qrcode' => "badges#qrcode", as: 'qrcode_badge'
  get 'badges/:id/assertion' => "badges#assertion", as: 'badge_assertion'
  resources :badges
  resources :attendees
  resources :tickets
  resources :ticket_types

  resources :notifications, only: [:index,:update]
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/badges/:event_id" => "badges#index", as: "event_badges"
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  #get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  #get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  get 'users/:id/badges' => 'user#assertions', as: 'user_badges'
  get 'users/events' => 'user#events', as: 'my_events'
  get 'users/news' => 'user#news', as: 'my_news'
  get 'events/:id/invitations' => 'events#invites', as: 'event_invites'
  post 'events/:id/unique' => 'events#unique', as: 'unique_event'
  post 'events/unique' => 'events#unique', as: 'new_unique_event'
  post 'events/:event_id/attendees/draw' => 'attendees#draw', as: 'draw_attendees'

  resources :events do
    resources :attendees, only: [:index]
    resources :schedule, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities do
    resources :members
    resources :invites
    resources :boards do
      resources :board_messages, only: [:new,:edit,:show,:update,:create,:destroy]
    end
    resources :contacts
  end
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
  has_one :event, through: :ticket
  validates :ticket, uniqueness: { scope: :user}
  after_create :send_ticket, :create_notification

  private

  def send_ticket
    unless self.user.email.include?('facebook')
      cal=self.event.create_calendar_entry
      TicketMailer.new_ticket(self,cal.to_ical).deliver_later
    end
  end

  def recipients
    [self.event]
  end
  def create_notification
    recipients.each do |recipient|
      Notification.create(recipient: recipient.user, user: user, notifiable: self, action: 'going')
    end
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource


  # GET /attendees
  # GET /attendees.json
  def index
    @event= Event.find(params[:event_id])
    if current_user.id.to_i===@event.user_id.to_i || current_user.has_role?(:admin)
      @attendees = @event.attendees.paginate(:page => params[:page],:per_page =>30 ).order('created_at DESC')
    else
      redirect_back(fallback_location: root_path, status: 403)
    end
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    begin
      @qr = RQRCode::QRCode.new( attendee_url(@attendee.id), :size => 5, :level => :h )
    rescue RQRCode::QRCodeRunTimeError => e
      logger.info "Manage qr error show #{e.inspect}"
    end
    if user_signed_in?
      if @attendee.user_id == current_user.id
        event = @attendee.ticket.event
        if event.start_at>=DateTime.now && event.end_at<=DateTime.now
          @attendee.validated=true
          @attendee.validated_at=DateTime.now
          @attendee.save
        end
      end
    end
    respond_to do |format|
      format.html  { render :layout => 'no_header' }
      format.js
      format.json
    end
  end

  # GET /attendees/new
  def new
    if current_user.has_role? :admin
      logger.info 'loaded'
      @attendee = Attendee.new
    else
      logger.info 'not loaded'
      redirect_back(fallback_location: root_path, status: 403)
    end
  end

  # GET /attendees/1/edit
  def edit
    unless current_user.has_role? :admin
      redirect_back(fallback_location: root_path, status: 403)
    end
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = current_user.attendees.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        begin
          @qr = RQRCode::QRCode.new( attendee_url(@attendee.id), :size => 5, :level => :h )
        rescue RQRCode::QRCodeRunTimeError => e
          logger.info "Manage qr error in create #{e.inspect}"
        end
        format.html { redirect_to @attendee, notice: t(:was_successfully_created) }
        format.json { render :show, status: :created, location: @attendee }
        format.js
      else
        logger.info @attendee.inspect
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: t(:was_successfully_updated) }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: t(:was_successfully_destroyed) }
      format.json { head :no_content }
    end
  end

  def draw
    result = 'false'
    @event = Event.find(params[:event_id])
    @winner = @event.attendees.where("won=false and attendees.user_id<>?",@event.user_id).order("Rand()").first
    @winner.won = true
    if @winner.save
      result = @winner.user.name
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:ticket_id, :user_id)
    end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_attendee.html.slim
          div class="row"
             div class="col-lg-12"
               div class="col-lg-2"
                 div class="text-center"
                   h1 class="display-2"
                     = @attendee.event.start_at.strftime("%b")
                   h2 class="display-3 text-danger"
                     = @attendee.event.start_at.strftime("%d")
                   h2 class="display-3"
                     = @attendee.event.start_at.strftime("%Y")
               div class="col-lg-7"
                 = image_tag @attendee.event.image.url(:ticket), class: "figure-img img-fluid rounded img-responsive"
               div class="col-lg-3"
                 css:
                     #qr table {
                       border-width: 0;
                       border-style: none;
                       border-color: #0000ff;
                       border-collapse: collapse;
                       }
                     #qr td {
                       border-left: solid 5px #000;
                       padding: 0;
                       margin: 0;
                       width: 0px;
                       height: 5px;
                       }
                     #qr td.black { border-color: #000; }
                     #qr td.white { border-color: #fff; }
                 div id="qr"
                   = raw @qr.as_html
             div class="col-lg-2"
               | &nbsp;
             div class="col-lg-10"
               p
                 = @attendee.event.title
               p
                 = @attendee.event.location
               p
                 strong
                   = t(:from)
                   | : &nbsp;
                 = @attendee.event.start_at.strftime("%I:%M %p")
                 strong
                   |  &nbsp;
                   = t(:to)
                   | : &nbsp;
                 = @attendee.event.end_at.strftime("%I:%M %p")

app/views/attendees/_form.html.slim
= form_for @attendee do |f|
  - if @attendee.errors.any?
    #error_explanation
      h2 = "#{pluralize(@attendee.errors.count, "error")} prohibited this attendee from being saved:"
      ul
        - @attendee.errors.full_messages.each do |message|
          li = message

  div class="form-group row"
    = f.label t(:ticket)
    = f.select :ticket_id, Ticket.all.collect {|c| [c.id]}
  div class="form-group row"
    = f.label t(:user)
    = f.select :user_id, User.all.collect {|c| [c.name,c.id]}
  div class="form-group row"
    = f.submit t(:save), class: "btn btn-primary"

app/views/attendees/create.js.erb
<% unless @attendee.id.nil? %>
    $('#ticket_content').html('<%= j render(@attendee) %>');
    $('#link_to_attendee').html('<%= link_to t(:print_version), attendee_path(@attendee), target: "_blank", class: "btn btn-primary"%>');
    $('#view_your_ticket').html('<%= link_to t(:view_your_ticket), attendee_path(@attendee), remote: true, class: "btn btn-success btn-lg btn-block" %>');
<% else %> 
  $('#ticket_content').html('<p> ups </p> ');
<% end %>
  $('#Event_Registration').hide();
  $('#show_ticket').modal('show');

app/views/attendees/draw.js.erb
<%if @winner.won==true %>
alert('El Ganador es: <%=@winner.user.name%>');
<%else%>
alert('something when wrong');
<%end%>

app/views/attendees/edit.html.slim
div class="clearfix"
  div class="container"
    div class="page-header"
      div class="row"
          h1
            = t(:attendee)
            | :
      div class="row"
        == render 'form'
      div class="row"
        => link_to t(:show), @attendee
        '|
        =< link_to t(:back), attendees_path

app/views/attendees/index.html.slim
div class="container"
    div class="col-lg-12"
        div class="page-header"
          div class="row"
           div class="col-lg-10"
            h3
              = t(:attendees)
              | :
            = t(:to_your_event)
            | : &nbsp;
            = @event.title
           div class="col-lg-2"
            = button_to t(:draw), draw_attendees_path(@event.id), remote: true, title: t(:draw_info) , data: {toggle: "tooltip", placement: "bottom"}, class: "btn btn-success  btn-sm text-right"
        div class=" text-center"
          = will_paginate @attendees, renderer: BootstrapPagination::Rails
          - count=0
          table class="table-responsive" style="width: 100%"
            thead
              tr style="text-align: left"
                th
                  | &nbsp;
                th style="text-align: left;width: 30%;"
                  = t(:attendee)
                th
                  | &nbsp;
                th style="text-aling: left;"
                  = t(:join)
                th style="text-align: left"
                  = t(:validated)
                th style="text-align: left"
                  = t(:validated_at)
                th style="text-algin: center"
                  = t(:won)
            tbody
              - if params[:page].nil?
                - count=0
              - else
                - if params[:page].to_i==1.to_i
                  - count=0
                - else
                  - count= 30*params[:page].to_i - 30
              - @attendees.each do |attendee|
                tr style="border-bottom:1pt solid black;"
                  td
                    = count+=1
                    | &nbsp;
                  td style="text-align: left; width: 30%;"
                    = attendee.user.name
                  td
                    | &nbsp;
                  td style="text-align: left"
                    = attendee.created_at.strftime("%d-%m-%Y %I:%M %p"  )
                  td style="text-align: center"
                    - if attendee.validated
                      i class="fa fa-check fa-1x"
                  td style="text-align: left"
                    = attendee.validated_at.strftime("%d-%m-%Y %I:%M %p"  ) unless attendee.validated_at.nil?
                  td style="text-align: center"
                    - if attendee.won
                      i class="fa fa-check fa-1x"
        br
        div class="row text-center"
          = will_paginate @attendees, renderer: BootstrapPagination::Rails

app/views/attendees/new.html.slim
div class="container"
    div class="col-lg-12"
      div class="page-header"
          h1
            = t(:attendees)
            | :
      div class="row"
        == render 'form'
      div class="row"
        = link_to t(:back), attendees_path

app/views/attendees/show.html.slim
  div class="container"
    div class="col-lg-12"
        div class="list-group"
          div class="list-group-item list-group-item-action flex-column align-items-start"
             = render @attendee
    div class="col-lg-12"
        p
         = sanitize(@attendee.event.description)

app/views/attendees/show.js.erb
$('#ticket_content').html('<%= j render(@attendee) %>');
$('#link_to_attendee').html('<%= link_to t(:print_version), attendee_path(@attendee), target: "_blank", class: "btn btn-primary"%>');
$('#show_ticket').modal('show');