config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'
Rails.application.routes.draw do
 resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end
  resources :feeds
  resources :planet, only: [:index,:show]
  resources :preferences, only: [:index,:update]
  resources :oportunities
  resources :profile_views
  resources :conversations, only: [:index,:create,:new] do
    resources :messages, only: [:index,:create]
  end

  get 'communities/:community/events' => 'events#index', as: 'community_events'
  get 'communities/:community_id/contacts/preview' => "contacts#preview", as: 'community_contact_preview'
  resources :badge_rules
  get 'badges/:uuid/claim' => "badges#claim", as: 'badge_claim'
  get 'badges/:uuid/qrcode' => "badges#qrcode", as: 'qrcode_badge'
  get 'badges/:id/assertion' => "badges#assertion", as: 'badge_assertion'
  resources :badges
  resources :attendees
  resources :tickets
  resources :ticket_types

  resources :notifications, only: [:index,:update]
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/ }
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/badges/:event_id" => "badges#index", as: "event_badges"
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  #get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  #get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  get 'users/:id/badges' => 'user#assertions', as: 'user_badges'
  get 'users/events' => 'user#events', as: 'my_events'
  get 'users/news' => 'user#news', as: 'my_news'
  get 'events/:id/invitations' => 'events#invites', as: 'event_invites'
  post 'events/:id/unique' => 'events#unique', as: 'unique_event'
  post 'events/unique' => 'events#unique', as: 'new_unique_event'
  post 'events/:event_id/attendees/draw' => 'attendees#draw', as: 'draw_attendees'

  resources :events do
    resources :attendees, only: [:index]
    resources :schedule, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities do
    resources :members
    resources :invites
    resources :boards do
      resources :board_messages, only: [:new,:edit,:show,:update,:create,:destroy]
    end
    resources :contacts
  end
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :assignments
  has_many :roles, :through => :assignments
  has_many :news
  has_many :pages
  has_many :carousels
  has_many :communities
  has_many :members
  has_many :events
  has_many :attendees
  has_many :own_badges, :class_name => :Badge, foreign_key: :owner_id
  has_many :user_badges
  has_many :badges, :through => :user_badges
  has_many :own_notifications, :class_name => :Notification
  has_many :notifications, foreign_key: :recipient_id
  has_many :board_messages
  has_many :own_conversations, :class_name => :Conversation
  has_many :conversations
  has_many :messages
  has_many :invites
  has_one :preference
  has_many :feeds
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  TEMP_EMAIL_PREFIX = 'change-me'
  TEMP_EMAIL_REGEX = /\Achange-me/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates :name,
       :presence => true #,
  #     :format => {:with=> /\A[\p{Word}\p{space}]*\z/, :message=> I18n.t(:no_special_characters) }
  validates :name, uniqueness: true
  has_attached_file :avatar,
           styles: { :project=>"400x400",:medium => "200x200>", :med_thumb => '100x100', :thumb => "40x40>" },
           :processors => [:cropper],
           default_url: ->(attachment) { ActionController::Base.helpers.asset_path("user_avatar.png") }
  validates_attachment_content_type :avatar, :content_type => /^image\/(png|gif|jpeg|jpg)/
  validate :domain_invalid?
  attr_accessor :crop_x, :crop_y, :crop_x2, :crop_y2, :crop_w, :crop_h, :crop_vy

  after_update :reprocess_image, :if => :cropping?
  after_create :reprocess_image, :if => :cropping?
  after_update :set_preference

  def self.find_for_oauth(auth, signed_in_resource = nil)
    #logger.info auth.inspect
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
    if user.nil?
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      unless email_is_verified
        if auth.provider=='facebook' and !auth.info.email.include?('facebook')
          email=auth.info.email
        else auth.provide=='github' and !auth.info.email.include?('github')
          email=auth.info.email
        end
      end
      #logger.info "email: #{email}"
      user = User.where(:email => email).first if email
      if user.nil?
        res = Net::HTTP.get_response(URI(auth.info.image + "?type=large"))
        case res
        when Net::HTTPSuccess then
          image= auth.info.image + "?type=large"
        when Net::HTTPRedirection then
          location=res['location']
          new_res = Net::HTTP.get_response(URI(location))
          if new_res.code.to_i==200.to_i
            image= location
          end
        else
          image = nil
        end
        #logger.info "res: #{image}"
        name = auth.extra.raw_info.name
        if name.nil?
          name = auth.info.name.nil? ? auth.info.nickname : auth.info.name
        end
         name = auth.info.username if name.nil?
        unless image.nil?
          user = User.new(
            name: name,
            #username: auth.info.nickname || auth.uid,
            email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}@#{auth.provider}.com",
            password: Devise.friendly_token[0,20],
            avatar: open(image)
          )
        else
          user = User.new(
            name: name,
            #username: auth.info.nickname || auth.uid,
            email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}@#{auth.provider}.com",
            password: Devise.friendly_token[0,20]
          )
        end
        user.skip_confirmation!
        user.save!
      else
        user.confirmed_at=DateTime.now.to_s(:db) if user.confirmed_at.nil?
        user.save!
      end
    end
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  rescue Exception => e
    logger.debug "Auth Fail with #{auth.provider}: #{e.inspect}"
    errors.add(:base, "Favor reportar este error al autenticar con #{auth.provider}: #{e.message}")
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  def domain_invalid?
    begin
      domain = self.email.split("@").last
      s = Socket.gethostbyname(domain)
    rescue SocketError
      errors.add(:email, :invalid_domain, not_allowed: " email domain is invalid")
      return false
    end
  end

  def send_devise_notification(notification, *args)

    devise_mailer.send(notification, self, *args).deliver_later

  end
  private

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def image_geometry(style = :original)
    tmpfile = avatar.queued_for_write[style]
    if tmpfile
      @geometry ||= {}
      @geometry[style] ||= Paperclip::Geometry.from_file(tmpfile)
    end
  end

  def reprocess_image
    image_geometry(:original)
    self.crop_h = 400
    self.crop_w = 400
    avatar.assign(avatar)
    avatar.save
  end

  def set_preference
    if self.preference.nil?
      preference = Preference.create(user_id: self.id, profile_view_id: 1,oportunity_id: 1)
      preference.save
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show,:assertions]
  before_action :set_user, only: [:show,:assertions]

  def show
    if @user
      @badges = @user.badges
      @communities = Community.joins(:members).where("members.user_id=?",@user.id)
      @events = @user.events.order("id desc").limit(6)
      @attended = Attendee.joins(:user).where("users.id=?",@user.id).order("created_at desc").limit(6)
      @news = @user.news.where("publish=true").order("id desc ").limit(6)

    end
  end

  def events
      @events = current_user.events.paginate(:page => params[:page],:per_page =>8 ).order('start_at DESC')
      render file: 'events/index'
  end

  def news
    @news = current_user.news.paginate(:page => params[:page],:per_page =>8 ).order('created_at DESC')
    render file: 'news/index'
  end
  def assertions
    user_badges = UserBadge.where("user_id=?",@user.id)
    badges=[]
    user_badges.each do |user_badge|
      first=UserBadge.where("badge_id=?",user_badge.badge_id).first
      last=UserBadge.where("badge_id=?",user_badge.badge_id).last
      times=UserBadge.where("badge_id=?",user_badge.badge_id).count
      badges << {:description=>user_badge.badge.description,
                 :tags=>user_badge.badge.tags,
                 :issue=>user_badge.created_at.to_time.to_i,
                 :image=>URI.join(request.url, user_badge.badge.image.url),
                 :first_awarded=>first.created_at.to_time.to_i,
                 :first_awarded_person=>first.user.name,
                 :last_awarded_person=>last.user.name,
                 :last_awarded=>last.created_at.to_time.to_i,
                 :id=>user_badge.badge.uuid,
                 :time_awarded=>times,
                 :name=>user_badge.badge.name}
    end
    percentile=UserBadge.where("user_id=?",@user.id).count.to_f/Badge.count.to_f
    data= UserBadge.find_by_sql("select user_id,count(*)  from user_badges group by user_id order by 2 desc")
    count=0
    rank=0
    data.each do |d|
     count+=1
     rank=count if d["user_id"]==@user.id
    end
    assertions={:user_count=>User.count, :rank=>rank,:avatar=>URI.join(request.url, @user.avatar.url),:percentile=>percentile,:assertions=>badges}
    render json: assertions

  end

  private
  def set_user
    numeric =  Float(params[:id]) != nil rescue false
    if numeric
      @user = User.find(params[:id])
    else
        @user = User.find_by_name(params[:id])
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/show.html.slim
div class="container"
 div class="col-lg-12"
    div class="page-header"
      - if notice
        div class="col-lg-12"
          div class="alert alert-dismissible alert-success"
            button type="button" class="close" data-dismiss="alert"
              | &times;
            = notice
    div class="col-lg-12"
      div class="col-lg-3"
        div class="card bg-light mb-3" style="max-width: 20rem;"
          div class="card-header"
          div class="card-body" style="text-align: center"
            p class="card-text"
              = image_tag @user.avatar.url(:medium), class: "img-circle img-fluid"
            h4 class="card-title"
              = @user.name
            - unless @badges.empty?
              = t(:view_user_like)
              | &nbsp;
              = link_to "Json", user_badges_path(@user.id)

      div class="col-lg-9"
        - unless @badges.empty?
          div class="panel panel-default"
            div class="panel-heading"
              = t(:my_badges) if @badges.count>0
            div class="panel-body"
              - @badges.each do |badge|
                = render  badge
        - unless @communities.empty?
          div class="panel panel-default"
            div class="panel-heading"
              = t(:my_communities)
            div class="panel-body"
              div class="list-group"
              - @communities.each do |community|
                div class="list-group-item col-lg-2 text-center" style="border: 0;"
                  = link_to community_url(community.subdomain), title: "#{community.name} - #{strip_tags(community.information).truncate(100)}" , data: {toggle: "tooltip", container: "body", placement: "bottom"} do
                    = image_tag community.logo.url(:thumb), alt: community.name
        - unless @events.empty?
          div class="panel panel-default"
            div class="panel-heading"
              = t(:my_recent_events)
            div class="panel-body"
              div class="list-group"
                - @events.each do |event|
                  div class="list-group-item col-lg-4" style="border: 0;"
                    = link_to event_url(event.subdomain),  title: "#{event.title} - #{strip_tags(event.description).truncate(100)}" , data: {toggle: "tooltip", container: "body", placement: "bottom"} do
                      = image_tag event.image.url(:medium), class: "img-responsive"
                    = event.start_at.strftime("%b %d %Y")
        - unless @attended.empty?
          div class="panel panel-default"
            div class="panel-heading"
              = t(:attended_to_this_events)
            div class="panel-body"
              div class="list-group"
                - @attended.each do |attend|
                  - event = attend.ticket.event
                  div class="list-group-item col-lg-4" style="border: 0;"
                    = link_to event_url(event.subdomain),  title: "#{event.title} - #{strip_tags(event.description).truncate(100)}" , data: {toggle: "tooltip", container: "body", placement: "bottom"} do
                      = image_tag event.image.url(:medium), class: "img-responsive"
                    = event.start_at.strftime("%b %d %Y")
        - unless @news.empty?
          div class="panel panel-default"
            div class="panel-heading"
              = t(:my_recent_news)
            div class="panel-body"
              div class="list-group"
                - @news.each do |article|
                   div class="list-group-item col-lg-4" style="border: 0;"
                    = link_to article.title, news_path(article), title: "#{strip_tags(article.news_content.content).truncate(100)}" , data: {toggle: "tooltip", container: "body", placement: "bottom"}